"""delete sprintprogress table

Revision ID: 0c592841fe3b
Revises: e95777984e57
Create Date: 2022-07-12 20:12:28.109234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c592841fe3b'
down_revision = 'e95777984e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprint_progress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('object_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('object_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
