"""Update User2

Revision ID: 27ea0eaeba1f
Revises: ee3287499823
Create Date: 2022-06-29 16:18:39.419199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ea0eaeba1f'
down_revision = 'ee3287499823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegram')
    # ### end Alembic commands ###
