"""upgrade User table

Revision ID: 2e7ee6779775
Revises: c8574d7fd82b
Create Date: 2022-06-27 00:23:11.189119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7ee6779775'
down_revision = 'c8574d7fd82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_column('user_pass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_pass', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
