"""added image column to the Content

Revision ID: b1d19d2039ec
Revises: 27ea0eaeba1f
Create Date: 2022-07-04 14:18:00.603841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d19d2039ec'
down_revision = '27ea0eaeba1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('image', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'image')
    # ### end Alembic commands ###
