"""added column type to the Content table

Revision ID: bea5aa1b67a7
Revises: e2fc94fcb501
Create Date: 2022-06-26 17:55:48.498167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea5aa1b67a7'
down_revision = 'e2fc94fcb501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('sprint_id', sa.Integer(), nullable=True))
    op.alter_column('content', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content', 'type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'content', 'sprint', ['sprint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.alter_column('content', 'type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('content', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('content', 'sprint_id')
    # ### end Alembic commands ###
