"""Init migrate

Revision ID: c8574d7fd82b
Revises: 
Create Date: 2022-06-26 23:47:45.496408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8574d7fd82b'
down_revision = None
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('sprint_id', sa.Integer(), nullable=True))
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('content', 'sprint', ['sprint_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('sprint_id')

    # ### end Alembic commands ###
