"""new progress model

Revision ID: e95777984e57
Revises: a0ef9d0dbb6a
Create Date: 2022-07-10 13:37:46.102191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95777984e57'
down_revision = 'a0ef9d0dbb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.Unicode(length=255), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprint_progress')
    # ### end Alembic commands ###
