"""Update User

Revision ID: ee3287499823
Revises: 2e7ee6779775
Create Date: 2022-06-29 16:17:35.626375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3287499823'
down_revision = '2e7ee6779775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegram')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
